services:
  - type: web
    name: cmonitoringsys-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://cmonitoringsys-app.onrender.com
