services:
  - type: web
    name: cmonitoringsys-app
    plan: free
    env: docker
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://cmonitoringsys-app.onrender.com
